---
collections:
  -
    name: community.general
    version: 7.4.0
  -
    name: ansible.posix
    version: 1.5.4
  -
    name: community.docker
    version: 3.4.8

roles:
  -
    name: geerlingguy.docker
    version: 6.1.0
